services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=vending_machine'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433'
