services:
  vending-machine-api:
    build:
      context: .
    ports:
      - "8080:8080"
#    environment:
#      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - database

  database:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: vending_machine_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: